### ISSUE TITLE
!important

### ISSUE THREAD

**Issue by bkniffler** [JakeCoxon/babel-plugin-css-to-js#4]
Hey, 
I tried using the !important flag, but it wasn't translated to my styles. 

Is this a missing feature?

**Comment by BjornMelgaard** [comment]
@bkniffler made pr above, tested it in my local project, nothing crashed, I hope @JakeCoxon note it, until that - `yarn add -D https://github.com/BjornMelgaard/babel-plugin-css-to-js\#my-build`

**Comment by JakeCoxon** [comment]
Fixed in 0.0.2 thanks to @BjornMelgaard
